FROM golang:1.15-alpine as builder
WORKDIR /app
RUN apk update && apk add make
COPY . .
RUN make all

FROM alpine:3.12
COPY --from=builder /app/bin/linux/reboot-agent /reboot-agent
CMD ["/reboot-agent"]