apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: reboot-agent
spec:
  selector:
    matchLabels:
      app: reboot-agent
  template:
    metadata:
      labels:
        app: reboot-agent
    spec:
      containers:
      - name: reboot-agent
        image: vtomasr5/demo-reboot-agent:latest
        command:
        - ./reboot-agent
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
